### ISSUE TITLE
Sugestão: fornecer o PDF do manuscrito após cada atualização

### ISSUE THREAD

**Issue by danielsource** [valdigleis/mcf#1]
Minha sugestão seria distribuir um PDF do manuscrito após cada atualização, como era feito no repositório anterior. Dessa forma, ficaria mais prático e fácil de acessar uma nova versão para quem não pudesse compilar no momento ou estivesse no celular.

**Comment by valdigleis** [comment]
Será feito @danielsource, estou apenas modificando algumas configurações de algumas macros utilizadas no modelo, quando terminar aí tudo será atualizando junto e o PDF ficará disponível!!!!

**Comment by valdigleis** [comment]
Será feito @danielsource, estou apenas modificando algumas configurações de algumas macros utilizadas no modelo, quando terminar aí tudo será atualizando junto e o PDF ficará disponível!!!!
